### ISSUE TITLE
Realm is not creating table for the class

### ISSUE THREAD

**Issue by amadofelipe** [remind101/auto-value-realm#2]
I wrote this class:
 
```
@AutoValue
public abstract class Invoice implements Parcelable, AvModel<$RealmInvoice> {

    @Nullable
    public abstract Integer something();

    @AutoValue.Builder
    abstract static public class Builder {
        public abstract Invoice build();
        public abstract Builder something(Integer something);
    }
}
```

I am trying to use it, but when I try to read/write from Realm, I get this exception:

```
io.realm.exceptions.RealmException: class com.my.package.model.$RealmInvoice is not part of the schema for this Realm.
                                                            at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:241)
                                                            at io.realm.DefaultRealmModuleMediator.getTableName(DefaultRealmModuleMediator.java:228)
                                                            at io.realm.RealmSchema.getTable(RealmSchema.java:296)
                                                            at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
                                                            at io.realm.RealmQuery.<init>(RealmQuery.java:138)
...
```

I noticed from the gradle output that Realm is processing other of my classes but none of those generated by this Autovalue extension:

```
19:11:52.610 [ERROR] [system.err] Note: Processing class OtherModel
19:11:52.612 [ERROR] [system.err] Note: Creating DefaultRealmModule
```

So, $RealmInvoice seem to be ignored by the Realm plugin.Therefore the DefaultRealmModuleMediator.java does not contain the class $RealmInvoice and that is why I am getting the exception.

Any ideas of what could be going on? Maybe when the Realm task is running before that class is generated? If so, any ideas of how to work around it?

Thanks!

**Comment by amadofelipe** [comment]
Ok. I think I fixed it by reordering the plugins in my build.gradle. It looks like the android-apt plugin must come before Realm plugin (not after):

```
apply plugin: 'com.neenbedankt.android-apt' // must be applied before 'realm-android'
apply plugin: 'realm-android'
```

UPDATE: Actually it was not fixed. I thought I have fixed because I was not using my main project. I was trying things out in a sample.

**Comment by amadofelipe** [comment]
I am attaching a sample project with the issue. The problem occurs only when there are others RealmObject subclasses in the project besides the ones generated by auto-value-realm processors.

[RealmExample.zip](https://github.com/remind101/auto-value-realm/files/659702/RealmExample.zip)
